### ISSUE TITLE
Create custom token using a service account ID

### ISSUE THREAD

**Issue by kanclalg** [firebase/firebase-admin-dotnet#106]
Hi, I'm trying to create custom token for specified service account from different service account. I'm following this guide: https://firebase.google.com/docs/auth/admin/create-custom-tokens#using_a_service_account_json_file (Using a service account ID).
When I configure it like that and try to generate a token, that token is invalid. So I started debugging:
https://github.com/firebase/firebase-admin-dotnet/blob/5397e845fef87124940ba99cb1225e6c04210ba2/FirebaseAdmin/FirebaseAdmin/Auth/FirebaseTokenFactory.cs#L74-L95
If I set debugger on here and set `serviceAccount` value to `null`, I get a valid token. So it seems like it's using wrong service account.

Can `app.Options.Credential.ToServiceAccountCredential()` be `null`? You cannot even initialize FirebaseApp without setting `Credential = GoogleCredential.GetApplicationDefault()`.

Shouldn't the logic be that it should first check if a service account ID is specified and invoke the IAM service, and only if not it should go for other cases?

**Comment by hiranya911** [comment]
> When I configure it like that and try to generate a token, that token is invalid.

What do you mean by that? The SDK cannot generate an "invalid" token as long as the service account used to sign it is valid. Unless you're using a service account from project A and using the resulting token to sign into project B.

> Can app.Options.Credential.ToServiceAccountCredential() be null?

Yes, some application default credential implementations are not of the `ServiceAccountCredential` type -- especially the ones that are auto discovered in managed cloud environments. See https://github.com/googleapis/google-api-dotnet-client/tree/master/Src/Support/Google.Apis.Auth/OAuth2

> Shouldn't the logic be that it should first check if a service account ID is specified and invoke the IAM service, and only if not it should go for other cases?

The SDK prefers `ServiceAccountCredential` over service account ID, as that is the fastest way to sign tokens. This is the established priority order in all Admin SDK implementations.

I'll keep this open in case you want to follow up on that "invalid token" issue. But as it stands, I don't see any direct action items for this repo.

**Comment by kanclalg** [comment]
> Unless you're using a service account from project A and using the resulting token to sign into project B.

Yes. That's what I'm trying to achieve. I'm using service account from project A, I set `ServiceAccountId` from another project B and expect to generate token with which I could sign into project B.

**Comment by hiranya911** [comment]
That's not allowed. When you're setting a service account ID, the SDK has to invoke the Cloud IAM API to sign the token remotely with that service account ID: https://cloud.google.com/iam/reference/rest/

That API call is authorized with the credentials you have specified (or application default credentials if unspecified). You cannot authorize an IAM API call with credentials from project A, and ask it to sign a token using a service account in project B.

**Comment by kanclalg** [comment]
But it's possible, @hiranya911 ? because if I set `serviceAccount` to `null` (debugging) it sets signer as that: `signer = new FixedAccountIAMSigner(app.Options.HttpClientFactory, app.Options.Credential, app.Options.ServiceAccountId);` in that case at first I get this error: 

> Permission iam.serviceAccounts.signBlob is required to perform this operation
> on service account projects/-/serviceAccounts/{your-service-account-id}.

this error is documentated here https://firebase.google.com/docs/auth/admin/create-custom-tokens

But if I add `Service Account Token Creator` role for service account from project A to project B IAM it works fine.

**Comment by hiranya911** [comment]
Yes, but this cross pollination of projects and service accounts is not something we wish to support or advertise. It's often very confusing to reason about the permissions of projects this way. Also this works today because we don't put the project ID in the IAM endpoint (notice the `/projects/-/` part in the error message). That might change in the future, or IAM might change how the project ID inference works. At very least we want to retain the flexibility to change such details in future implementations.

You should look into using one of the following options to implement your use case.

### Option 1: Init the SDK with credentials for project B

As it stands, I don't see why you use a service account from project A while trying to create custom tokens for project B. Just use credentials for project B if at all possible.

### Option 2: Use two `FirebaseApp` instances:

```
var project_A_app = FirebaseApp.Create(new AppOptions
{
   // Service account for project A
});

var project_B_app = FirebaseApp.Create(new AppOptions
{
   // Service account or ADC for project B
   // Service Account ID
}, "CustomTokenApp");
```

Use the latter for creating tokens and the former for interacting with project A.

### Option 3: Implement a custom `GoogleCredential` implementation

Wrap project A's service account credential inside a custom `GoogleCredential` so it doesn't get picked for local token signing. You will likely have to wrap the service account in an `ICredential` first. See how the `AccessTokenCredential` is implemented to get an idea: https://github.com/googleapis/google-api-dotnet-client/blob/master/Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs#L143
