### ISSUE TITLE
Issue with connecting to Firebase

### ISSUE THREAD

**Issue by lkishor** [firebase/firebase-admin-dotnet#126]
Hi, I have created a .Net API that sends a notification to users.
It was working fine till yesterday, and Now I am getting below error:
FirebaseMessagingException - Timed out while making an API call: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

I suspect, there is something wrong with the network connectivity. But while trying to send notification via Postman on "https://fcm.googleapis.com/fcm/send", The connection is successful.

Is there a list of URLs that I can whitelist to solve this problem?
Any help would be greatly appreciated.
Thanks in advance.

**Comment by hiranya911** [comment]
The above URL and https://oauth2.googleapis.com/token for FCM API calls. If you're seeing this error consistently, please contact support and provide more project-specific information.

**Comment by lkishor** [comment]
Thanks @hiranya911, I will get this URL whitelisted on my company network and try..I'll update if that works.

**Comment by MSchmack** [comment]
@lkishor  Getting the same issue with http posts, did the above resolve your issue?

**Comment by lkishor** [comment]
No it didn't, We had to whitelist whole IP address range used by Google..

**Comment by hiranya911** [comment]
Are you behind a proxy? Is that the problem here? Where did you have to whitelist Google IPs?

If it's matter of a proxy, now you can specify a `HttpClientFactory` when initializing the SDK: https://firebase.google.com/docs/reference/admin/dotnet/class/firebase-admin/app-options#class_firebase_admin_1_1_app_options_1a828e351aeabd2bb4ea99c39601273e4d

There's a sample factory implementation for proxy support here: https://medium.com/google-cloud/accessing-google-cloud-apis-though-a-proxy-fe46658b5f2a

**Comment by lkishor** [comment]
Servers are behind a Corporate Firewall, only known IP addresses are whitelisted. This was done by the Network team in the company..

**Comment by MSchmack** [comment]
Also behind a corporate firewall. We had no issues until recently with just the fcm.googleapis.com fqdn on tcp open. Periodically the issue seems to resolve and creep back up.

Whitelisting the whole range doesnt seem wise from a security point of view.

**Comment by MSchmack** [comment]
Alright the issue on our side is resolved. The problem was not due to firebase directly, its the way firebase changes its ip's like many google services incredibly fast, so fast that our firewall compared the target ip of our request with the current one of fcm.googleapis.com and already noticed a missmatch - Atleast that's the current assumption.

**Comment by lkishor** [comment]
What's the preferred way of white listing on corporate firewall in this case?

Please share once you reach a solution..

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by MSchmack** [comment]
Luckily it's just outward traffic (assuming it's a application firewall) so with some arguing once it's proven that the FQDN solution doesn't work you can probably get a internet any rule which will resolve the issue. 
I can't speak for process at your company but IP range's wont work for us as google mentions that the ranges are updated every month and a firewall change request is not applied in a day at that scale, the change request may take multiple days up to a week to be resolved which potentially takes down the application.

Preferred options are single IP's to ranges and FQDN if the firewall can handle it, which in this case it cannot.
