### ISSUE TITLE
Support for voip notification

### ISSUE THREAD

**Issue by jphillips05** [firebase/firebase-admin-dotnet#97]
Doe this support Pushkit for iOS?

**Comment by hiranya911** [comment]
No it doesn't. See https://stackoverflow.com/questions/37326450/does-firebase-cloud-messaging-support-voip-pushkit-services for a related discussion.

**Comment by lingxiao** [comment]
Any updates?

**Comment by hiranya911** [comment]
It's not something we are actively working on. If you have a specific use case, please file a feature request with Firebase Support.

**Comment by alxsad** [comment]
@hiranya911 It's really important thing, I don't know why FCM still does not support APNS VOIP messages.

**Comment by hiranya911** [comment]
It's a product decision, and this repo is not the right place to have those discussions. I suggest you reach out to Firebase Support and file a feature request with them: https://firebase.google.com/support

**Comment by tomerpeled** [comment]
This is crucial requirement in order to implement custom notification handling, such as:
custom notification view, decision whether to show notifications to the user, save the notification content into some local db and enjoy fast app loading (with all the data already prepared, instead of fetching it from the server on login), etc.
For example, whatsapp/telegram are using the voip notifications to handle their push notifications customization (as explained above).
https://stackoverflow.com/questions/60815763/how-does-the-whatsapp-web-client-still-work-with-the-latest-ios-update-sdk-vers

With the remote notifications the above is not possible and with background notifications it is not guaranteed to be received...

* notice however, that it seems that whatsapp/telegram are using some special entitlement for that:
com.apple.developer.pushkit.unrestricted-voip

**Comment by felippi** [comment]
Any update about that???

**Comment by tomerpetel** [comment]
Any update? any plans in supporting PushKit in Firebase?

**Comment by tamimattafi** [comment]
Any update? It would've been very cool to use a single SDK for both types of pushes, rather than using FCM and APNs through SNS or OneSignal for example
